/** Human-readable labels for timeline events (client-safe). */
export const EVENT_LABELS: Record<string, string> = {
  lead_created: "Lead discovered",
  lead_enriched: "Business details enriched",
  lead_enrichment_failed: "Enrichment failed",
  lead_scored: "Lead scored",
  lead_qualified: "Qualified as a potential buyer",
  lead_disqualified: "Disqualified",
  lead_status_changed: "Status changed",
  lead_imported: "Imported from CSV",
  discovery_started: "Discovery started",
  discovery_completed: "Discovery completed",
  discovery_failed: "Discovery failed",
  campaign_created: "Campaign created",
  campaign_started: "Campaign launched",
  campaign_paused: "Campaign paused",
  campaign_resumed: "Campaign resumed",
  campaign_completed: "Campaign completed",
  lead_added_to_campaign: "Added to campaign",
  outreach_generated: "Personalised pitch generated",
  message_approved: "Message approved",
  message_suppressed: "Message blocked by do-not-contact",
  email_sent: "Email sent",
  email_delivered: "Email delivered",
  email_opened: "Email opened",
  email_clicked: "Link clicked",
  email_replied: "Email reply received",
  email_bounced: "Email bounced",
  email_failed: "Email failed",
  email_unsubscribed: "Unsubscribed",
  whatsapp_sent: "WhatsApp sent",
  whatsapp_delivered: "WhatsApp delivered",
  whatsapp_read: "WhatsApp read",
  whatsapp_received: "WhatsApp reply received",
  whatsapp_failed: "WhatsApp failed",
  call_prepared: "Call brief prepared",
  call_started: "Call started",
  call_answered: "Call answered",
  call_completed: "Call completed",
  call_failed: "Call failed",
  reply_classified: "AI classified the reply",
  opt_out: "Opted out of contact",
  sequence_stopped: "Sequence stopped",
  followup_scheduled: "Follow-up scheduled",
  meeting_created: "Meeting booked",
  quote_created: "Quote created",
  quote_sent: "Quote sent",
  quote_viewed: "Quote viewed",
  quote_accepted: "Quote accepted",
  quote_rejected: "Quote declined",
  quote_expired: "Quote expired",
  deal_created: "Deal created",
  deal_stage_changed: "Deal stage changed",
  deal_won: "Deal won",
  deal_lost: "Deal lost",
  task_created: "Task created",
  task_completed: "Task completed",
  note_added: "Note added",
  workflow_started: "Workflow started",
  workflow_completed: "Workflow completed",
  workflow_failed: "Workflow failed",
  ai_request: "AI request",
  ai_response: "AI response",
};

export type EventTone = "neutral" | "accent" | "success" | "warning" | "danger";

export function eventTone(type: string): EventTone {
  if (/(won|accepted|qualified|replied|received|answered|meeting_created)$/.test(type)) return "success";
  if (/(failed|bounced|lost|rejected|opt_out|unsubscribed|suppressed|disqualified)$/.test(type)) return "danger";
  if (/(sent|generated|prepared|classified|scheduled|started)$/.test(type)) return "accent";
  return "neutral";
}
